blog/urls.py
from django.urls import path

from blog.views import create_or_edit_post,post_detail,post_list

app_name = 'blog'

urlpatterns = [
    path('create_post/',create_or_edit_post,  name='create_post'),
    path('edit_post/<int:_id>/',create_or_edit_post,  name='edit_post'),
    path('', post_list, name='post_list'),
    path('post_detail/<int:post_id>', post_detail, name='post_detail'),

]

codelnmain/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from accounts.views import profile

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/<int:pk>', profile, name='view_profile'),
    path('projects/', include('projects.urls', namespace='projects')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('', include('frontend.urls', namespace='frontend')),
    path('', include('classroom.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('martor/', include('martor.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token',obtain_jwt_token),
    path('api-token-refress',refresh_jwt_token),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.page_404'
handler500 = 'frontend.views.page_500'

frontend/urls.py
from django.urls import path

from frontend.views import index, UserList
from frontend.views import home,activity,tracker,update_candidateprojects,\
    sample,inprogress,projectinvites,update_finished,invites,\
    projectdetails,pendingproject,terms,dev,pricing,howitworks,privacy,\
    report,credits,onboarddevs,onboardrecruiters,seedevs,seerecruiters,manageprojects,managetransactions,\
    editproject,deleteproject,addproject,edittransactions\
    ,deletetransaction,buildproject,calltoapply,apply,opencalltracker,competitions,newproject,\
    passedquizzes,failedquizzes,pickcandidates,update_finishedopencall,portfolio,experience,closetransaction,\
    editportfolioproject,about,management,grading,storegrades,analytics,ProfileUpdate,Profileget,Talentget,Experienceget,\
    Portfolioget,AllUsers,Userget,AllExperienceget,AllPortfolioget,ProjectAssignment
from frontend.tasks import reminderforprofiledevs,applyreminder,massmail,submission
from accounts.views import update_profile

app_name = 'frontend'
urlpatterns = [
    path('', index, name='index'),
    path('home/', home, name='home'),
    path('tracker/<int:id>', tracker, name='tracker'),
    path('dev', dev, name='dev'),
    path('howitworks', howitworks, name='howitworks'),
    path('pricing', pricing, name='pricing'),
    path('report/<int:candidate_id>/<int:transaction_id>', report, name='report'),
    path('privacy', privacy, name='privacy'),
    path('terms', terms, name='terms'),
    path('sample', sample, name='sample'),
    path('credits', credits, name='credits'),
    path('inprogress/', inprogress, name='inprogress'),
    path('invites/', invites, name='invites'),
    path('pendingproject/<int:transaction_id>', pendingproject, name='pendingproject'),
    path('projectdetails/<int:id>', projectdetails, name='projectdetails'),
    path('activity/', activity, name='my-activity'),
    path('update_profile/', update_profile, name='update-profile'),
    path('projectinvites/<int:transaction_id>/', projectinvites, name='update-profile'),
    path('update_finished/<int:candidateproject_id>/<int:transaction_id>', update_finished,
         name='update_finished'),
    path('update_finishedopencall/<int:project_id>/<int:transaction_id>', update_finishedopencall,
         name='update_finishedopencall'),
    path('update_candidateprojects/<int:candidateproject_id>/<int:transaction_id>', update_candidateprojects,
         name='update_candidateprojects'),
    path('onboarddevs',onboarddevs,name='onboarddevs'),
    path('onboardrecruiters',onboardrecruiters,name='onboardrecruiters'),
    path('seedevs',seedevs,name='seedevs'),
    path('seerecruiters',seerecruiters,name='seerecruiters'),
    path('manageprojects',manageprojects,name='manageprojects'),
    path('managetransactions',managetransactions,name='managetransactions'),
    path('editproject/<int:project_id>',editproject,name='editproject'),
    path('deleteproject/<int:project_id>',deleteproject,name='deleteproject'),
    path('edittransactions/<int:transaction_id>',edittransactions,name='edittransactions'),
    path('deletetransaction/<int:transaction_id>',deletetransaction,name='deletetransaction'),
    path('closetransaction/<int:transaction_id>',closetransaction,name='closetransaction'),
    path('addproject',addproject,name='addproject'),
    path('calltoapply',calltoapply,name='calltoapply'),
    path('buildproject',buildproject,name='buildproject'),
    path('passedquizzes',passedquizzes,name='passedquizzes'),
    path('failedquizzes',failedquizzes,name='failedquizzes'),
    path('competitions',competitions,name='competitions'),
    path('apply/<int:opportunity_id>',apply,name='apply'),
    path('opencalltracker/<int:trans_id>',opencalltracker,name='opencalltracker'),
    path('pickcandidates/<int:trans_id>/<int:candidate_id>',pickcandidates,name='pickcandidates'),
    path('reminderforprofiledevs',reminderforprofiledevs,name='reminderforprofiledevs'),
    path('applyreminder', applyreminder, name='applyreminder'),
    path('massmail', massmail, name='massmail'),
    path('submission', submission, name='submission'),
    path('portfolio',portfolio,name='portfolio'),
    path('analytics',analytics,name='analytics'),

    path('newproject',newproject,name='newproject'),
    path('experience',experience,name='experience'),
    path('editportfolioproject/<int:project_id>',editportfolioproject,name='editportfolioproject'),
    path('about',about,name='about'),
    path('management',management,name='management'),
    path('grading/<int:candidate_id>/<int:transaction_id>',grading,name='grading'),
    path('storegrades/<int:candidate_id>/<int:transaction_id>',storegrades,name='storegrades'),
    path('users/', UserList.as_view()),
    path('allusers/', AllUsers.as_view()),
    path('updater/<int:pk>', ProfileUpdate.as_view()),
    path('getuser/<int:pk>', Userget.as_view()),
    path('getprofile/<int:pk>', Profileget.as_view()),
    path('gettalent/<int:pk>', Talentget.as_view()),
    path('getexperience/<int:candidate_id>', Experienceget.as_view()),
    path('getportofolio/<int:candidate_id>', Portfolioget.as_view()),
    path('getallexperience', AllExperienceget.as_view()),
    path('getallportofolio', AllPortfolioget.as_view()),
    path('asignproject', ProjectAssignment.as_view()),




]

marketplace/urls.py
from django.urls import path

from marketplace.views import job_list, job_details, apply_for_job, manage_posted_jobs, pick_candidate, \
    select_candidate, dev_pool, dev_details, process_payment, payment_canceled, payment_done, add_dev_to_wish_list,\
    mydevs,paid_dev_details,create_or_edit_job,dev_data,Myjobsrequests,Jobsapplicants,\
    Specificjob,SpecificJobsapplicants,Myjobapplication,JobUpdate,JobCreate,JobsList,PickReject,PickRecommended,JobUnpublish,\
    DevRequestpick,DevRequests,CandidateManager,MyApplicants,Jobdetails,JobApply,CandidateJobs

app_name = 'marketplace'

urlpatterns = [

    path('job_list/', job_list, name='job_list'),
    path('job_details/<int:id>/', job_details, name='job_details'),
    path('apply_for_job/<int:job_id>/', apply_for_job, name='apply_for_job'),

    path('post_job/', create_or_edit_job, name='post_job'),
    path('edit_job/<int:_id>/',create_or_edit_job,  name='edit_job'),
    path('manage_posted_jobs/', manage_posted_jobs, name='manage_posted_jobs'),
    path('pick_candidate/<int:job_id>/<int:dev_id>/', pick_candidate, name='pick_candidate'),
    path('select_candidate/<int:job_id>/<int:dev_id>/', select_candidate, name='select_candidate'),
    path('dev_pool/', dev_pool, name='dev_pool'),
    path('dev_data/', dev_data, name='dev_data'),
    path('mydevs/', mydevs, name='mydevs'),
    path('dev_details/<int:dev_id>', dev_details, name='dev_details'),
    path('paid_dev_details/<int:dev_id>', paid_dev_details, name='paid_dev_details'),
    path('add_dev_to_wish_list', add_dev_to_wish_list, name='add_dev_to_wish_list'),
    path('process_payment', process_payment, name='process_payment'),
    path('payment_canceled', payment_canceled, name='payment_canceled'),
    path('payment_done', payment_done, name='payment_done'),
    path('mydevs/<int:owner>', DevRequests.as_view()),
    path('myapplicants/<int:owner>',MyApplicants.as_view()),
    path('pickdev', DevRequestpick.as_view()),
    path('myjobs/<int:posted_by>', Myjobsrequests.as_view()),
    path('jobapplicants/<int:job>', Jobsapplicants.as_view()),
    path('specificjob/<int:pk>', Specificjob.as_view()),
    path('specificjobapplicants/<int:job>', SpecificJobsapplicants.as_view()),
    path('updatejob/<int:pk>', JobUpdate.as_view()),
    path('unpublishjob/<int:pk>', JobUnpublish.as_view()),
    path('pickreject/<int:pk>', PickReject.as_view()),
    path('candidatemanager/<int:pk>', CandidateManager.as_view()),
    path('pickrecommended', PickRecommended.as_view()),
    path('createjob', JobCreate.as_view()),
    path('alljobs', JobsList.as_view()),
    path('myjobapplication/<int:candidate>/<int:job>', Myjobapplication.as_view()),
    path('jobdetails/<int:pk>', Jobdetails.as_view()),
    path('applyjob', JobApply.as_view()),
    path('candidatejobs/<int:candidate>', CandidateJobs.as_view()),

]

projects/urls.py
from django.urls import path
from projects.views import project_list, project,categories,devtypes,Projects,ProjectDetails,Allprojects,RecentProjects,MyRecentProjects,RecommendedProjects

app_name = 'projects'
urlpatterns = [
    #path('', project_categories, name='categories'y),
    path('all-projects/<int:type_id>/', project_list, name='all-projects'),
    path('devtypes/<int:dev_id>/', devtypes, name='devtypes'),
    path('categories/', categories, name='categories'),
    path('project/<int:id>/', project, name='project'),
    path('projects/<int:id>', Projects.as_view()),
    path('recommendedprojects/<int:id>', RecommendedProjects.as_view()),
    path('allprojects', Allprojects.as_view()),
    path('projectdetails/<int:pk>', ProjectDetails.as_view()),
    path('recentprojects/<int:id>', RecentProjects.as_view()),
    path('myrecentprojects/<int:id>', MyRecentProjects.as_view()),

]

transactions/urls.py
from django.urls import path

from transactions.views import process_transaction, my_invites, \
    sourcing, transaction_view,success,opencall

app_name = 'transactions'

urlpatterns = [
    # path('', project_categories, name='categories'),
    path('transaction/<int:id>/', transaction_view, name='transaction'),
    path('process_transaction/<int:id>/', process_transaction, name='process_transaction'),
    path('my-invites/', my_invites, name='my-invites'),
    path('sourcing/', sourcing, name='sourcing'),
    path('success/', success, name='success'),
    path('opencall/<int:id>/', opencall, name='opencall'),

]

marketplace/models.py
import json

from django.conf import settings
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from django.contrib.auth.models import User
from separatedvaluesfield.models import SeparatedValuesField
from projects.models import Project

class Job(models.Model):
    ENGAGEMENT_TYPE = (
        ('Full-time', 'Full-time'),
        ('Part-time', 'Part-time'),
        ('Contract', 'Contract'),
        ('Remote', 'Remote'),
        ('Freelance', 'Freelance'),
    )

    JOB_ROLE = (
        ('Full Stack Developer', 'Full Stack Developer'),
        ('Frontend Developer', 'Frontend Developer'),
        ('Backend  Developer', 'Backend  Developer'),
        ('Android  Developer', 'Android  Developer'),
        ('Graphic Designer', 'Graphic Designer'),
        ('IOS Developer', 'IOS Developer'),
        ('Data Scientist', 'Data Scientist'),
    )

    DEV_EXPERIENCE = (
        ('Entry', 'Entry'),
        ('Junior', 'Junior'),
        ('Mid-Level', 'Mid-Level'),
        ('Senior', 'Senior'),
    )
    company = models.CharField(max_length=300)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    job_role = models.CharField(max_length=30, choices=JOB_ROLE, default='Full Stack Developer')
    dev_experience = models.CharField(max_length=30, choices=DEV_EXPERIENCE, default='Mid-Level')
    engagement_type = models.CharField(max_length=30, choices=ENGAGEMENT_TYPE, default='Full-time')
    tech_stack = models.CharField(max_length=500)
    num_devs_wanted = models.IntegerField(default=1)
    location = CountryField(null=True, max_length=30)
    remuneration = models.CharField(max_length=45, help_text='in dollars ($)')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    position_filled = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    deadline = models.DateTimeField(null=True, blank=True)


    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.title


class JobApplication(models.Model):
    job = models.ForeignKey(Job, related_name='job_applications', on_delete=models.CASCADE)
    candidate = models.ForeignKey(User, on_delete=models.CASCADE, related_name='devs')
    selected = models.BooleanField(default=False)
    stage =models.CharField(max_length=500, null=True)
    interviewstarttime = models.DateTimeField(null=True,blank=True)
    interviewendtime = models.DateTimeField(null=True, blank=True)
    notes = models.CharField(max_length=1500,null=True)
    recruiter = models.ForeignKey(User, related_name='jobrecruiter', on_delete=models.CASCADE,null=True,blank=True)
    test_stage = models.CharField(max_length=500, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100, null=True)
    candidatename = models.CharField(max_length=100, null=True)
    report = models.CharField(max_length=500, null=True)
    interviewstatus = models.CharField(max_length=500, null=True)
    eventcolor = models.CharField(max_length=100, null=True,default='blue')


class DevRequest(models.Model):
    owner = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE)
    developer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='devaccount',null=True,)
    paid = models.BooleanField(default=False)
    stage = models.CharField(max_length=500, null=True)
    interviewstarttime = models.DateTimeField(null=True, blank=True)
    interviewendtime = models.DateTimeField(null=True, blank=True)
    notes = models.CharField(max_length=1500, null=True)
    test_stage = models.CharField(max_length=500, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100, null=True)
    candidatename = models.CharField(max_length=100, null=True)
    report = models.CharField(max_length=500, null=True)
    interviewstatus = models.CharField(max_length=500, null=True)
    eventcolor = models.CharField(max_length=100, null=True, default='blue')

marketplace/forms.py
from django import forms
from .models import Job


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ('posted_by', 'created', 'updated', 'position_filled',)

marketplace/templates/marketplace/recruiter/jobs/create.html
{% extends 'recruiterbase.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <main role="main" class="col-md-12 ml-lg-auto  col-lg-10 px-4 ">
        <div class="d-none d-lg-block">
            <nav class="navbar  navbar-light fixed-top fine border-bottom">
                <h5>Create a Job</h5>
                <ul class="nav ml-auto">
                    {% if request.user.is_authenticated %}


                        <li class="nav-item">
                            <a href="{% url 'account_logout' %}" style="color: black" class="nav-link">Logout</a>
                        </li>

                    {% else %}

                        <li class="nav-item">
                            <a href="{% url 'account_login' %}" style="color: black" class="nav-link">Login</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}" style="color: black" class="nav-link">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>

        <!-----md devices adaptation------>
        <div class="container d-lg-none">
            <nav class=" navbar loginbar navbar-expand-md navbar-light fixed-top ">
                <h5 style="color: white">Source for Developers</h5>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                    <span style="color: white" data-feather="menu"></span>
                </span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" style="color: white" href="#" id="navbarDropdown"
                               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Menu
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'frontend:my-activity' %}">Ongoing tests</a>
                                <a class="dropdown-item" href="{% url 'projects:categories' %}">Create a test</a>
                                <a class="dropdown-item" href="{% url 'transactions:sourcing' %}">Source candidates</a>
                            </div>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a href="/home" style="color: white" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'account_logout' %}" style="color: white" class="nav-link">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'account_login' %}" style="color: white" class="nav-link">Login</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'account_signup' %}" style="color: white" class="nav-link">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>

        <div class="d-none d-lg-block" style="margin-top: 8%">

        </div>

        <div class="d-lg-none" style="margin-top: 5em">

        </div>
        <div class="shadow-lg p-3 mb-5 bg-white ">
            <form action="." method="post" class="form">
                {% csrf_token %}
                <h6>Job details</h6>
                <hr>
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Job Title</label>
                        {% bootstrap_field job_form.title placeholder=False show_label=False %}
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Company name</label>
                        {% bootstrap_field job_form.company placeholder=False show_label=False %}
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Location</label>
                        {% bootstrap_field job_form.location placeholder=False show_label=False %}
                    </div>

                </div>


                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Job role</label>
                        {% bootstrap_field job_form.job_role show_label=False %}
                    </div>

                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Experience</label>
                        {% bootstrap_field job_form.dev_experience show_label=False %}
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Contract type</label>
                        {% bootstrap_field job_form.engagement_type placeholder='react, angular, python etc' show_label=False %}
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Tech Stack</label>
                        {% bootstrap_field job_form.tech_stack placeholder=False show_label=False %}
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Number of Devs needed</label>
                        {% bootstrap_field job_form.num_devs_wanted show_label=False %}
                    </div>

                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <label>Range of Monthly remuneration ($)</label>
                        {% bootstrap_field job_form.remuneration placeholder='1000-1500' show_label=False %}
                    </div>


                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Job Description</label>
                    <textarea name="description" id="textarea" ></textarea>

                </div>
                <div class="d-flex justify-content-center">
                    <button class="btn primary1  col-3" style="color: white" type="submit">Add Job</button>
                </div>

            </form>

        </div>


    </main>
{% endblock %}

{% block script %}
<script>
    $(document).ready( function () {
    var description = {{ job | safe }};
    $('#textarea').each(function () {
    var editor = new Jodit(this);
    editor.value = description
});
} );
</script>

{% endblock %}

marketplace/templates/marketplace/recruiter/jobs/list.html
{% extends 'recruiterbase.html' %}
{% load bootstrap4 %}
{% block title %}
    recruiter dashboard
{% endblock %}
{% load static %}
{% block content %}
    <main role="main" class="col-md-12 col-lg-10 ml-lg-auto   px-4 ">
        <div class="d-none d-lg-block">
            <nav class="navbar  navbar-light fixed-top fine border-bottom">
                <h5>Job listings</h5>
                <ul class="nav ml-auto">


                    {% if request.user.is_authenticated %}


                        <li class="nav-item">
                            <a href="{% url 'account_logout' %}" style="color: black" class="nav-link">Logout</a>
                        </li>

                    {% else %}

                        <li class="nav-item">
                            <a href="{% url 'account_login' %}" style="color: black" class="nav-link">Login</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}" style="color: black" class="nav-link">Register</a>
                        </li>
                    {% endif %}


                </ul>
            </nav>
        </div>

        <!-----md devices adaptation------>
        <div class="container d-lg-none">
            <nav class=" navbar loginbar navbar-expand-md navbar-light fixed-top ">
                <a class="logoadapt h5" style="text-decoration: none" href="/">Job listings</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                    <span style="color: white" data-feather="menu"></span>
                </span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" style="color: white" href="#" id="navbarDropdown"
                               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Sidebar menu options
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
{#                                <a class="dropdown-item" href="{% url 'frontend:inprogress'%}">Ongoing#}
{#                                    Projects</a>#}
                                <a class="dropdown-item" href="/update_profile/">My profile</a>
                            </div>
                        </li>
                        {% if request.user.is_authenticated %}

                            <li class="nav-item">
                                <a href="{% url 'account_logout' %}" style="color: white" class="nav-link">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'account_login' %}" style="color: white" class="nav-link">Login</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'account_signup' %}" style="color: white" class="nav-link">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        <div class="d-none d-lg-block" style="margin-top: 6%">

        </div>
        <div class="d-lg-none" style="margin-top: 7em">

        </div>



        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Job Title</th>
                <th scope="col">Company</th>

                <th scope="col">Candidates Applied</th>
                <th scope="col">Candidates Selected</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for job_detail in job_details %}
                <tr>
                    <td> {{ forloop.counter }} </td>
                    <td>{{ job_detail.0.title }}</td>
                    <td>{{ job_detail.0.company}}</td>

                    <td>{{ job_detail.1}}</td>
                    <td>{{ job_detail.2 }}</td>
                    <td>
                    <a href="{% url 'marketplace:job_details' job_detail.0.id %}">
                                Manage Job
                    </a>

                    </td>
                </tr>

            {% endfor %}


            </tbody>
        </table>


    </main>

{% endblock %}

marketplace/templates/marketplace/recruiter/jobs/wizard.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form }}
    {% endfor %}
{% else %}
    {{ wizard.form }}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
{% endif %}
<input type="submit" value="{% trans "submit" %}"/>
</form>
{% endblock %}