blog/urls.py
from django.urls import path

from blog.views import create_or_edit_post,post_detail,post_list

app_name = 'blog'

urlpatterns = [
    path('create_post/',create_or_edit_post,  name='create_post'),
    path('edit_post/<int:_id>/',create_or_edit_post,  name='edit_post'),
    path('', post_list, name='post_list'),
    path('post_detail/<int:post_id>', post_detail, name='post_detail'),

]

codelnmain/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from accounts.views import profile

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/<int:pk>', profile, name='view_profile'),
    path('projects/', include('projects.urls', namespace='projects')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('', include('frontend.urls', namespace='frontend')),
    path('', include('classroom.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('martor/', include('martor.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token',obtain_jwt_token),
    path('api-token-refress',refresh_jwt_token),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.page_404'
handler500 = 'frontend.views.page_500'

frontend/urls.py
from django.urls import path

from frontend.views import index, UserList
from frontend.views import home,activity,tracker,update_candidateprojects,\
    sample,inprogress,projectinvites,update_finished,invites,\
    projectdetails,pendingproject,terms,dev,pricing,howitworks,privacy,\
    report,credits,onboarddevs,onboardrecruiters,seedevs,seerecruiters,manageprojects,managetransactions,\
    editproject,deleteproject,addproject,edittransactions\
    ,deletetransaction,buildproject,calltoapply,apply,opencalltracker,competitions,newproject,\
    passedquizzes,failedquizzes,pickcandidates,update_finishedopencall,portfolio,experience,closetransaction,\
    editportfolioproject,about,management,grading,storegrades,analytics,ProfileUpdate,Profileget,Talentget,Experienceget,\
    Portfolioget,AllUsers,Userget,AllExperienceget,AllPortfolioget,ProjectAssignment
from frontend.tasks import reminderforprofiledevs,applyreminder,massmail,submission
from accounts.views import update_profile

app_name = 'frontend'
urlpatterns = [
    path('', index, name='index'),
    path('home/', home, name='home'),
    path('tracker/<int:id>', tracker, name='tracker'),
    path('dev', dev, name='dev'),
    path('howitworks', howitworks, name='howitworks'),
    path('pricing', pricing, name='pricing'),
    path('report/<int:candidate_id>/<int:transaction_id>', report, name='report'),
    path('privacy', privacy, name='privacy'),
    path('terms', terms, name='terms'),
    path('sample', sample, name='sample'),
    path('credits', credits, name='credits'),
    path('inprogress/', inprogress, name='inprogress'),
    path('invites/', invites, name='invites'),
    path('pendingproject/<int:transaction_id>', pendingproject, name='pendingproject'),
    path('projectdetails/<int:id>', projectdetails, name='projectdetails'),
    path('activity/', activity, name='my-activity'),
    path('update_profile/', update_profile, name='update-profile'),
    path('projectinvites/<int:transaction_id>/', projectinvites, name='update-profile'),
    path('update_finished/<int:candidateproject_id>/<int:transaction_id>', update_finished,
         name='update_finished'),
    path('update_finishedopencall/<int:project_id>/<int:transaction_id>', update_finishedopencall,
         name='update_finishedopencall'),
    path('update_candidateprojects/<int:candidateproject_id>/<int:transaction_id>', update_candidateprojects,
         name='update_candidateprojects'),
    path('onboarddevs',onboarddevs,name='onboarddevs'),
    path('onboardrecruiters',onboardrecruiters,name='onboardrecruiters'),
    path('seedevs',seedevs,name='seedevs'),
    path('seerecruiters',seerecruiters,name='seerecruiters'),
    path('manageprojects',manageprojects,name='manageprojects'),
    path('managetransactions',managetransactions,name='managetransactions'),
    path('editproject/<int:project_id>',editproject,name='editproject'),
    path('deleteproject/<int:project_id>',deleteproject,name='deleteproject'),
    path('edittransactions/<int:transaction_id>',edittransactions,name='edittransactions'),
    path('deletetransaction/<int:transaction_id>',deletetransaction,name='deletetransaction'),
    path('closetransaction/<int:transaction_id>',closetransaction,name='closetransaction'),
    path('addproject',addproject,name='addproject'),
    path('calltoapply',calltoapply,name='calltoapply'),
    path('buildproject',buildproject,name='buildproject'),
    path('passedquizzes',passedquizzes,name='passedquizzes'),
    path('failedquizzes',failedquizzes,name='failedquizzes'),
    path('competitions',competitions,name='competitions'),
    path('apply/<int:opportunity_id>',apply,name='apply'),
    path('opencalltracker/<int:trans_id>',opencalltracker,name='opencalltracker'),
    path('pickcandidates/<int:trans_id>/<int:candidate_id>',pickcandidates,name='pickcandidates'),
    path('reminderforprofiledevs',reminderforprofiledevs,name='reminderforprofiledevs'),
    path('applyreminder', applyreminder, name='applyreminder'),
    path('massmail', massmail, name='massmail'),
    path('submission', submission, name='submission'),
    path('portfolio',portfolio,name='portfolio'),
    path('analytics',analytics,name='analytics'),

    path('newproject',newproject,name='newproject'),
    path('experience',experience,name='experience'),
    path('editportfolioproject/<int:project_id>',editportfolioproject,name='editportfolioproject'),
    path('about',about,name='about'),
    path('management',management,name='management'),
    path('grading/<int:candidate_id>/<int:transaction_id>',grading,name='grading'),
    path('storegrades/<int:candidate_id>/<int:transaction_id>',storegrades,name='storegrades'),
    path('users/', UserList.as_view()),
    path('allusers/', AllUsers.as_view()),
    path('updater/<int:pk>', ProfileUpdate.as_view()),
    path('getuser/<int:pk>', Userget.as_view()),
    path('getprofile/<int:pk>', Profileget.as_view()),
    path('gettalent/<int:pk>', Talentget.as_view()),
    path('getexperience/<int:candidate_id>', Experienceget.as_view()),
    path('getportofolio/<int:candidate_id>', Portfolioget.as_view()),
    path('getallexperience', AllExperienceget.as_view()),
    path('getallportofolio', AllPortfolioget.as_view()),
    path('asignproject', ProjectAssignment.as_view()),




]

payments/urls.py
from django.urls import path
from .views import process_payment, payment_canceled, flutterwavepayment_done,process_opencalloption1,process_opencalloption2,process_opencalloption3

app_name = 'payments'

urlpatterns = [
    path('pay/<int:id>/', process_payment, name='pay'),
    path('opencall1/<int:id>/', process_opencalloption1, name='payoption1'),
    path('opencall2/<int:id>/', process_opencalloption2, name='payoption2'),
    path('opencall3/<int:id>/', process_opencalloption3, name='payoption3'),

    path('canceled/<int:id>/', payment_canceled, name='canceled'),
    path('flutterdone/<int:id>/', flutterwavepayment_done, name='flutter-done'),
]


# flutterwave confirmation url

projects/urls.py
from django.urls import path
from projects.views import project_list, project,categories,devtypes,Projects,ProjectDetails,Allprojects,RecentProjects,MyRecentProjects,RecommendedProjects

app_name = 'projects'
urlpatterns = [
    #path('', project_categories, name='categories'y),
    path('all-projects/<int:type_id>/', project_list, name='all-projects'),
    path('devtypes/<int:dev_id>/', devtypes, name='devtypes'),
    path('categories/', categories, name='categories'),
    path('project/<int:id>/', project, name='project'),
    path('projects/<int:id>', Projects.as_view()),
    path('recommendedprojects/<int:id>', RecommendedProjects.as_view()),
    path('allprojects', Allprojects.as_view()),
    path('projectdetails/<int:pk>', ProjectDetails.as_view()),
    path('recentprojects/<int:id>', RecentProjects.as_view()),
    path('myrecentprojects/<int:id>', MyRecentProjects.as_view()),

]

transactions/urls.py
from django.urls import path

from transactions.views import process_transaction, my_invites, \
    sourcing, transaction_view,success,opencall

app_name = 'transactions'

urlpatterns = [
    # path('', project_categories, name='categories'),
    path('transaction/<int:id>/', transaction_view, name='transaction'),
    path('process_transaction/<int:id>/', process_transaction, name='process_transaction'),
    path('my-invites/', my_invites, name='my-invites'),
    path('sourcing/', sourcing, name='sourcing'),
    path('success/', success, name='success'),
    path('opencall/<int:id>/', opencall, name='opencall'),

]

payments/models.py
from django.db import models

# Create your models here.

payments/views.py
from django.conf import settings
from django.contrib.sites.models import Site
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm

from transactions.models import Transaction


# Create your views here.

def process_payment(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    transaction.stage = 'make-payment'
    amount=int(transaction.amount())
    print(transaction.allcandidates().count())
    transaction.save()
    return render(request, 'payments/process.html',
                  {'amount':amount, 'transaction':transaction})
def process_opencalloption1(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    transaction.stage = 'make-payment'
    amount= int(400)
    print(transaction.allcandidates().count())
    transaction.save()
    return render(request, 'payments/process.html',
                  {'amount':amount, 'transaction':transaction})

def process_opencalloption2(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    transaction.stage = 'make-payment'
    amount=int(600)
    print(transaction.allcandidates().count())
    transaction.save()
    return render(request, 'payments/process.html',
                  {'amount':amount, 'transaction':transaction})

def process_opencalloption3(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    transaction.stage = 'make-payment'
    amount=int(800)
    print(transaction.allcandidates().count())
    transaction.save()
    return render(request, 'payments/process.html',
                  {'amount':amount, 'transaction':transaction})
@csrf_exempt
def payment_canceled(request, id):
    # redirect to add candidates
    return redirect(reverse('transactions:process_transaction', args=[id]))


@csrf_exempt
def flutterwavepayment_done(request, id):
    transaction = Transaction.objects.get(id=id)
    transaction.stage = 'payment-verified'
    transaction.paid = True
    transaction.save()
    # verifypaymentsuccess
    return redirect(reverse('transactions:process_transaction', args=[transaction.id]))

payments/templates/payments/payment.html
{% extends 'recruiterbase.html' %}
{% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}
{% load static %}
{% block content %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3  fley">
        <div class="navbar fixed-top fine border-bottom">

            <h5>Payment</h5>

            <nav>

                <ul class="nav ">
                    <!-- Authentication Links -->
                    <li><a class="nav-item" href="/pricing">Pricing</a></li>
                    <li class="nav-item">
                        <span data-feather="user">

                        </span>
                        {{ user.username }}
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'account_logout' %}" class="navbar-item w3-opacity"
                               title="Logout">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-item" href="{% url 'account_login' %}" class="navbar-item">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item" href="{% url 'account_signup' %}" class="navbar-item">Register</a>
                        </li>
                    {% endif %}


                </ul>

            </nav>
        </div>

    </div>

    <div class="row">

    <div class="col-lg-6" style="margin: auto">
    <div class="card" style="width: 28em;box-shadow:0 20px 50px rgba(0,0,0,.1);">
        <img class="card-img-top" style="width: 75%;margin: auto" src="/static/frontend/images/ill/card.svg"
             alt="Card image cap">

        <div class="card-body">
            <div class=" text-center h5" style="padding-top: 10%">Payment methods</div>
            <hr>
            <div class="row" style="margin: auto">
                <div class="col-lg-4">
                    <h6 style="margin-top:10% ">Flutterwave</h6>
                </div>
                <div class="col-lg-3">
                    <form style="text-align: -webkit-center;">
                        <script src="https://api.ravepay.co/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
                        <a onClick="payWithRave('{{ amount }}')"><img style="width: 10rem"
                                                                      src="/static/frontend/images/flutter.svg"></a>

                    </form>


                </div>
            </div>
        </div>
    </div>

    <script>


        const API_publicKey = "FLWPUBK-37536a50fc02bed5bddf5ebe89a18e7c-X";
        const SuccessUrl = '{% url 'payments:flutter-done' transaction.id %}';
        const CancelledUrl = '{% url 'payments:canceled' transaction.id%}';

        function payWithRave(amnt) {
            var x = getpaidSetup({
                PBFPubKey: API_publicKey,
                customer_email: '{{ transaction.user.email }}',
                amount: amnt,
                customer_phone: "234099940409",
                currency: "USD",
                payment_method: "both",
                txref: {{ transaction.id }},
                meta: [{
                    metaname: "transactionID",
                    metavalue: "Codeln2019"
                }],
                onclose: function () {
                },
                callback: function (response) {
                    var txref = response.tx.txRef; // collect txRef returned and pass to a 					server page to complete status check.
                    console.log("This is the response returned after a charge", response);
                    if (
                        response.tx.chargeResponseCode === "00" ||
                        response.tx.chargeResponseCode === "0"
                    ) {

                        window.location.href = SuccessUrl;
                    } else {
                        // redirect to a failure page.
                        window.location.href = CancelledUrl;
                    }

                    x.close(); // use this to close the modal immediately after payment.
                }
            });
        }
    </script>
{% endblock %}

payments/templates/payments/process.html
{% extends 'recruiterbase.html' %}
{% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}
{%load static %}
{% block content %}
    <main role="main" class="col-md-12 ml-lg-auto  col-lg-10 px-4 ">
    <div class="d-none d-lg-block">
        <nav class="navbar  navbar-light fixed-top fine border-bottom">
                    <h5 >Checkout</h5>
                    <ul class="nav ml-auto">



            {% if request.user.is_authenticated %}

            <li class="nav-item">
                <a  href="{% url 'account_logout' %}" style="color: black" class="nav-link" >Logout</a>
            </li>

            {% else %}

            <li class="nav-item">
                <a  href="{% url 'account_login' %}" style="color: black" class="nav-link" >Login</a>
            </li>
            <li class="nav-item">
                <a  href="{% url 'account_signup' %}" style="color: black" class="nav-link" >Register</a>
            </li>
            {% endif %}


    </ul>
                </nav>
    </div>

    <!-----md devices adaptation------>
    <div class="container d-lg-none">
        <nav class=" navbar loginbar navbar-expand-md navbar-light fixed-top ">
            <h5 class="logoadapt h5" style="text-decoration: none" href="/home">Checkout</h5>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span  class="navbar-toggler-icon">
                    <span style="color: white" data-feather="menu"></span>
                </span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" style="color: white"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menu
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'frontend:my-activity' %}" >Ongoing tests</a>
                            <a class="dropdown-item" href="{% url 'projects:categories' %}">Create a test</a>
                            <a class="dropdown-item" href="{% url 'transactions:sourcing' %}">Source candidates</a>
                        </div>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a  href="/home" style="color: white" class="nav-link" >Home</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'account_logout' %}" style="color: white" class="nav-link" >Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a  href="{% url 'account_login' %}" style="color: white" class="nav-link" >Login</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'account_signup' %}" style="color: white" class="nav-link" >Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    <div class="d-none d-lg-block" style="margin-top: 8%">

</div >

    <div class="d-lg-none"  style="margin-top: 7em">

</div>
    <div class="row">

    <div class="col-lg-6 col-md-12 d-flex justify-content-center " style="margin-left: auto;margin-right: auto">
    <div class="card" style="width: 28em;box-shadow:0 20px 50px rgba(0,0,0,.1);">
        <img class="card-img-top img-fluid" style="width: 69%;margin: auto" src="/static/frontend/images/ill/card.svg" alt="Card image cap">

        <div class="card-body">
            <div class=" text-center h5" style="padding-top: 10%">Payment methods</div>
            <hr>
            <div class="row" style="margin: auto">
                <div class="col-lg-6 col-md-12">
                    <h6 class="text-center" style="margin-top:3% ">Flutterwave:</h6>
                </div>
                <div class="col-lg-3 col-md-12">
                    <form style="text-align: -webkit-center;">
                        <script src="https://api.ravepay.co/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
                        <a onClick="payWithRave('{{amount}}')"><img class="btn btn-outline-primary" style="width: 10rem" src="/static/frontend/images/flutter.svg"></a>

                    </form>


                </div>
            </div>
        </div>
    </div>

    <script>


        const API_publicKey = "FLWPUBK-37536a50fc02bed5bddf5ebe89a18e7c-X";
        const SuccessUrl = '{% url 'payments:flutter-done' transaction.id %}';
        const CancelledUrl = '{% url 'payments:canceled' transaction.id %}';

        payWithRave(amnt) {
            var x = getpaidSetup({
                PBFPubKey: API_publicKey,
                customer_email: '{{ transaction.user.email }}',
                amount: amnt,
                customer_phone: "234099940409",
                currency: "USD",
                payment_method: "both",
                txref: {{ transaction.id }},
                meta: [{
                    metaname: "transactionID",
                    metavalue: "Codeln2019"
                }],
                onclose: function () {
                },
                callback: function (response) {
                    var txref = response.tx.txRef; // collect txRef returned and pass to a 					server page to complete status check.
                    console.log("This is the response returned after a charge", response);
                    if (
                        response.tx.chargeResponseCode === "00" ||
                        response.tx.chargeResponseCode === "0"
                    ) {

                        window.location.href = SuccessUrl;
                    } else {
                        // redirect to a failure page.
                        window.location.href = CancelledUrl;
                    }

                    x.close(); // use this to close the modal immediately after payment.
                }
            });
        }
    </script>
{% endblock %}

</div>
</div>
</main>