blog/urls.py
from django.urls import path

from blog.views import create_or_edit_post,post_detail,post_list

app_name = 'blog'

urlpatterns = [
    path('create_post/',create_or_edit_post,  name='create_post'),
    path('edit_post/<int:_id>/',create_or_edit_post,  name='edit_post'),
    path('', post_list, name='post_list'),
    path('post_detail/<int:post_id>', post_detail, name='post_detail'),

]

classroom/urls.py
from django.urls import include, path

from .views import students, teachers

urlpatterns = [


    path('students/', include(([
        path('', students.quizlist, name='quiz_list'),
        path('taken/', students.taken_quizlist, name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take, name='take'),
        path('tests/', students.student_registration, name='tests'),
        path('retake/<int:quizid>/<int:studentid>',students.retake, name='retake')
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.quizlist, name='quiz_change_list'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.updatequiz, name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.quizresults, name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
    ], 'classroom'), namespace='teachers')),
]

codelnmain/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from accounts.views import profile

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/<int:pk>', profile, name='view_profile'),
    path('projects/', include('projects.urls', namespace='projects')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('', include('frontend.urls', namespace='frontend')),
    path('', include('classroom.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('martor/', include('martor.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token',obtain_jwt_token),
    path('api-token-refress',refresh_jwt_token),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.page_404'
handler500 = 'frontend.views.page_500'

frontend/urls.py
from django.urls import path

from frontend.views import index, UserList
from frontend.views import home,activity,tracker,update_candidateprojects,\
    sample,inprogress,projectinvites,update_finished,invites,\
    projectdetails,pendingproject,terms,dev,pricing,howitworks,privacy,\
    report,credits,onboarddevs,onboardrecruiters,seedevs,seerecruiters,manageprojects,managetransactions,\
    editproject,deleteproject,addproject,edittransactions\
    ,deletetransaction,buildproject,calltoapply,apply,opencalltracker,competitions,newproject,\
    passedquizzes,failedquizzes,pickcandidates,update_finishedopencall,portfolio,experience,closetransaction,\
    editportfolioproject,about,management,grading,storegrades,analytics,ProfileUpdate,Profileget,Talentget,Experienceget,\
    Portfolioget,AllUsers,Userget,AllExperienceget,AllPortfolioget,ProjectAssignment
from frontend.tasks import reminderforprofiledevs,applyreminder,massmail,submission
from accounts.views import update_profile

app_name = 'frontend'
urlpatterns = [
    path('', index, name='index'),
    path('home/', home, name='home'),
    path('tracker/<int:id>', tracker, name='tracker'),
    path('dev', dev, name='dev'),
    path('howitworks', howitworks, name='howitworks'),
    path('pricing', pricing, name='pricing'),
    path('report/<int:candidate_id>/<int:transaction_id>', report, name='report'),
    path('privacy', privacy, name='privacy'),
    path('terms', terms, name='terms'),
    path('sample', sample, name='sample'),
    path('credits', credits, name='credits'),
    path('inprogress/', inprogress, name='inprogress'),
    path('invites/', invites, name='invites'),
    path('pendingproject/<int:transaction_id>', pendingproject, name='pendingproject'),
    path('projectdetails/<int:id>', projectdetails, name='projectdetails'),
    path('activity/', activity, name='my-activity'),
    path('update_profile/', update_profile, name='update-profile'),
    path('projectinvites/<int:transaction_id>/', projectinvites, name='update-profile'),
    path('update_finished/<int:candidateproject_id>/<int:transaction_id>', update_finished,
         name='update_finished'),
    path('update_finishedopencall/<int:project_id>/<int:transaction_id>', update_finishedopencall,
         name='update_finishedopencall'),
    path('update_candidateprojects/<int:candidateproject_id>/<int:transaction_id>', update_candidateprojects,
         name='update_candidateprojects'),
    path('onboarddevs',onboarddevs,name='onboarddevs'),
    path('onboardrecruiters',onboardrecruiters,name='onboardrecruiters'),
    path('seedevs',seedevs,name='seedevs'),
    path('seerecruiters',seerecruiters,name='seerecruiters'),
    path('manageprojects',manageprojects,name='manageprojects'),
    path('managetransactions',managetransactions,name='managetransactions'),
    path('editproject/<int:project_id>',editproject,name='editproject'),
    path('deleteproject/<int:project_id>',deleteproject,name='deleteproject'),
    path('edittransactions/<int:transaction_id>',edittransactions,name='edittransactions'),
    path('deletetransaction/<int:transaction_id>',deletetransaction,name='deletetransaction'),
    path('closetransaction/<int:transaction_id>',closetransaction,name='closetransaction'),
    path('addproject',addproject,name='addproject'),
    path('calltoapply',calltoapply,name='calltoapply'),
    path('buildproject',buildproject,name='buildproject'),
    path('passedquizzes',passedquizzes,name='passedquizzes'),
    path('failedquizzes',failedquizzes,name='failedquizzes'),
    path('competitions',competitions,name='competitions'),
    path('apply/<int:opportunity_id>',apply,name='apply'),
    path('opencalltracker/<int:trans_id>',opencalltracker,name='opencalltracker'),
    path('pickcandidates/<int:trans_id>/<int:candidate_id>',pickcandidates,name='pickcandidates'),
    path('reminderforprofiledevs',reminderforprofiledevs,name='reminderforprofiledevs'),
    path('applyreminder', applyreminder, name='applyreminder'),
    path('massmail', massmail, name='massmail'),
    path('submission', submission, name='submission'),
    path('portfolio',portfolio,name='portfolio'),
    path('analytics',analytics,name='analytics'),

    path('newproject',newproject,name='newproject'),
    path('experience',experience,name='experience'),
    path('editportfolioproject/<int:project_id>',editportfolioproject,name='editportfolioproject'),
    path('about',about,name='about'),
    path('management',management,name='management'),
    path('grading/<int:candidate_id>/<int:transaction_id>',grading,name='grading'),
    path('storegrades/<int:candidate_id>/<int:transaction_id>',storegrades,name='storegrades'),
    path('users/', UserList.as_view()),
    path('allusers/', AllUsers.as_view()),
    path('updater/<int:pk>', ProfileUpdate.as_view()),
    path('getuser/<int:pk>', Userget.as_view()),
    path('getprofile/<int:pk>', Profileget.as_view()),
    path('gettalent/<int:pk>', Talentget.as_view()),
    path('getexperience/<int:candidate_id>', Experienceget.as_view()),
    path('getportofolio/<int:candidate_id>', Portfolioget.as_view()),
    path('getallexperience', AllExperienceget.as_view()),
    path('getallportofolio', AllPortfolioget.as_view()),
    path('asignproject', ProjectAssignment.as_view()),




]

marketplace/urls.py
from django.urls import path

from marketplace.views import job_list, job_details, apply_for_job, manage_posted_jobs, pick_candidate, \
    select_candidate, dev_pool, dev_details, process_payment, payment_canceled, payment_done, add_dev_to_wish_list,\
    mydevs,paid_dev_details,create_or_edit_job,dev_data,Myjobsrequests,Jobsapplicants,\
    Specificjob,SpecificJobsapplicants,Myjobapplication,JobUpdate,JobCreate,JobsList,PickReject,PickRecommended,JobUnpublish,\
    DevRequestpick,DevRequests,CandidateManager,MyApplicants,Jobdetails,JobApply,CandidateJobs

app_name = 'marketplace'

urlpatterns = [

    path('job_list/', job_list, name='job_list'),
    path('job_details/<int:id>/', job_details, name='job_details'),
    path('apply_for_job/<int:job_id>/', apply_for_job, name='apply_for_job'),

    path('post_job/', create_or_edit_job, name='post_job'),
    path('edit_job/<int:_id>/',create_or_edit_job,  name='edit_job'),
    path('manage_posted_jobs/', manage_posted_jobs, name='manage_posted_jobs'),
    path('pick_candidate/<int:job_id>/<int:dev_id>/', pick_candidate, name='pick_candidate'),
    path('select_candidate/<int:job_id>/<int:dev_id>/', select_candidate, name='select_candidate'),
    path('dev_pool/', dev_pool, name='dev_pool'),
    path('dev_data/', dev_data, name='dev_data'),
    path('mydevs/', mydevs, name='mydevs'),
    path('dev_details/<int:dev_id>', dev_details, name='dev_details'),
    path('paid_dev_details/<int:dev_id>', paid_dev_details, name='paid_dev_details'),
    path('add_dev_to_wish_list', add_dev_to_wish_list, name='add_dev_to_wish_list'),
    path('process_payment', process_payment, name='process_payment'),
    path('payment_canceled', payment_canceled, name='payment_canceled'),
    path('payment_done', payment_done, name='payment_done'),
    path('mydevs/<int:owner>', DevRequests.as_view()),
    path('myapplicants/<int:owner>',MyApplicants.as_view()),
    path('pickdev', DevRequestpick.as_view()),
    path('myjobs/<int:posted_by>', Myjobsrequests.as_view()),
    path('jobapplicants/<int:job>', Jobsapplicants.as_view()),
    path('specificjob/<int:pk>', Specificjob.as_view()),
    path('specificjobapplicants/<int:job>', SpecificJobsapplicants.as_view()),
    path('updatejob/<int:pk>', JobUpdate.as_view()),
    path('unpublishjob/<int:pk>', JobUnpublish.as_view()),
    path('pickreject/<int:pk>', PickReject.as_view()),
    path('candidatemanager/<int:pk>', CandidateManager.as_view()),
    path('pickrecommended', PickRecommended.as_view()),
    path('createjob', JobCreate.as_view()),
    path('alljobs', JobsList.as_view()),
    path('myjobapplication/<int:candidate>/<int:job>', Myjobapplication.as_view()),
    path('jobdetails/<int:pk>', Jobdetails.as_view()),
    path('applyjob', JobApply.as_view()),
    path('candidatejobs/<int:candidate>', CandidateJobs.as_view()),

]

projects/urls.py
from django.urls import path
from projects.views import project_list, project,categories,devtypes,Projects,ProjectDetails,Allprojects,RecentProjects,MyRecentProjects,RecommendedProjects

app_name = 'projects'
urlpatterns = [
    #path('', project_categories, name='categories'y),
    path('all-projects/<int:type_id>/', project_list, name='all-projects'),
    path('devtypes/<int:dev_id>/', devtypes, name='devtypes'),
    path('categories/', categories, name='categories'),
    path('project/<int:id>/', project, name='project'),
    path('projects/<int:id>', Projects.as_view()),
    path('recommendedprojects/<int:id>', RecommendedProjects.as_view()),
    path('allprojects', Allprojects.as_view()),
    path('projectdetails/<int:pk>', ProjectDetails.as_view()),
    path('recentprojects/<int:id>', RecentProjects.as_view()),
    path('myrecentprojects/<int:id>', MyRecentProjects.as_view()),

]

transactions/urls.py
from django.urls import path

from transactions.views import process_transaction, my_invites, \
    sourcing, transaction_view,success,opencall

app_name = 'transactions'

urlpatterns = [
    # path('', project_categories, name='categories'),
    path('transaction/<int:id>/', transaction_view, name='transaction'),
    path('process_transaction/<int:id>/', process_transaction, name='process_transaction'),
    path('my-invites/', my_invites, name='my-invites'),
    path('sourcing/', sourcing, name='sourcing'),
    path('success/', success, name='success'),
    path('opencall/<int:id>/', opencall, name='opencall'),

]

frontend/models.py
from django.contrib.auth.models import User
from django.db import models

from marketplace.models import Job
from django_countries.fields import CountryField
from projects.models import Language, Framework ,Project
from transactions.models import Transaction
from separatedvaluesfield.models import SeparatedValuesField

# Create your models here.
class candidatesprojects(models.Model):
    stage = models.CharField(default='awaiting candidate', max_length=100)
    candidate = models.ForeignKey(User, on_delete=models.CASCADE,null=True,)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE,null=True,)




class submissions(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    demo = models.CharField(null=True, max_length=400)
    repo = models.CharField(null=True, max_length=400)

class Portfolio(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(null=True, max_length=200)
    description = models.CharField(null=True, max_length=400)
    repository_link = models.CharField(null=True, max_length=400)
    demo_link = models.CharField(null=True, max_length=400)
    verified = models.BooleanField(default=False)
    tech_tags = models.CharField(max_length=500, blank=True, null=True, )


class Experience(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(null=True, max_length=100)
    company = models.CharField(null=True, max_length=100)
    description = models.CharField(null=True, max_length=100)
    location = CountryField(null=True, max_length=30)
    duration = models.IntegerField(null=True)
    tech_tags = models.CharField(max_length=500, blank=True, null=True, )

class Report(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    requirements= SeparatedValuesField(null=True,max_length=150,token=',')
    keycompitency = SeparatedValuesField(null=True,max_length=150,token=',')
    grading = SeparatedValuesField(null=True,max_length=150,token=',')
    score = models.IntegerField(null=True)
    github = models.CharField(null=True, max_length=300)

frontend/templates/frontend/credits.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Icon credits</title>
</head>
<body>
<div>Icon by <a href="/icon/django-2" target="_blank">Icon Mafia</a></div>
<div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
<div>Icons made by <a href="https://www.flaticon.com/authors/nikita-golubev" title="Nikita Golubev">Nikita Golubev</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
<div>Icons made by <a href="https://www.flaticon.com/authors/prettycons" title="prettycons">prettycons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
<div>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
<div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
<div>Icons made by <a href="https://www.flaticon.com/authors/maxim-basinski" title="Maxim Basinski">Maxim Basinski</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
</body>
</html>

frontend/templates/frontend/index.html
{% extends 'base.html' %}
{% block content %}

Welcome, {{ user.profile }}
{% endblock %}

frontend/templates/frontend/jobs.html
{% extends 'base3.html' %}
{% load bootstrap4 %}
{% load cloudinary %}
{% load static %}
{% load staticfiles %}
{% block title %}
    Job board
{% endblock %}
{% load static %}
{% block content %}

    <div class="jumbotron jumbotron2">
        <div class="container">
            <div class="">

                <div class=" h3 text-center d-none d-lg-block " style="color: white">Job board</div>

                <div class="d-lg-none h5 text-center" style="color: white;margin-top: 4em;">Job board</div>
            </div>
        </div>
    </div>

    <div class="row" style="margin-right: 0;margin-left: 0">
        <div class="col-lg-8" style="margin-right: auto;margin-left: auto">

            {% if request.user.is_authenticated %}
                {% if request.user.profile.user_type == 'developer' %}
                    {% if request.user.profile.file  %}



                    {% else %}
                        <div id='backend_upload'>
                            <div class="alert alert-primary" role="alert">
                                Upload your cv to activate apply button(pdf format is preferred)
                            </div>
                            <form action="{% url 'marketplace:job_list' %}" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}

                                {% bootstrap_field backend_form.file show_label=False %}
                                <input class="btn btn-sm btn-primary" type="submit" value="Upload">
                            </form>
                        </div>
                    {% endif %}
                {% endif %}
            {% endif %}
            <br>

            {% if applied_jobs %}
                {% for app in applied_jobs %}
                    <div class="shadow-lg p-3 mb-5 bg-white rounded">
                        {{ app.job.title }} ({{ app.job.engagement_type }})
                        <br>

                        <span data-feather="map-pin"></span> {{ app.job.location.name }} |
                        <span data-feather="codepen"></span> {{ app.job.tech_stack }} {% if app.job.remuneration %} |

                        {{ app.job.remuneration }} /month
                    {% endif %}


                        <hr>
                        {{ app.job.description|safe }}
                        <br>
                        {% if app.selected %}
                            <span class="badge btn-primary mt-2"
                                  style="background-color: #b627a1">Picked for next stage</span>
                        {% elif app.selected == False %}
                            <span class="badge btn-primary mt-2"
                                  style="background-color: #28bbbb">Applied</span>

                        {% endif %}

                    </div>
                {% endfor %}

            {% endif %}

            {% if jobs %}
                {% for job in jobs %}
                    <div class="shadow-lg p-3 mb-5 bg-white rounded">
                        {{ job.title }} ({{ job.engagement_type }})
                        <br>

                        <span data-feather="map-pin"></span> {{ job.location.name }} |
                        <span data-feather="codepen"></span> {{ job.tech_stack }} {% if job.remuneration %} |

                        {{ job.remuneration }} /month
                    {% endif %}


                        <hr>
                        {{ job.description|safe }}

                        <form action="{% url 'marketplace:apply_for_job' job.id %}" method="post" class="form">
                            {% csrf_token %}
                            {% if request.user.is_authenticated %}
                                {% if request.user.profile.user_type == 'developer' %}
                                    {% if request.user.profile.file  %}
                                        <input class="btn theme--dark primary mt-3 "
                                               style="border-radius: 0; margin: auto; color: white" type="submit"
                                               value="Apply">
                                        {% else %}
                                        <a style="color:white" onclick="alert('PLease upload cv')"
                                       class="btn btn-warning mt-3">
                                        Apply
                                    </a>
                                    {% endif %}
                                {% else %}
                                    <a style="color:white" onclick="alert('Only available to Developer profiles')"
                                       class="btn btn-warning mt-3">
                                        Apply
                                    </a>
                                {% endif %}
                            {% else %}
                                <a style="color:white" href="{% url 'marketplace:apply_for_job' job.id %}"
                                   class="btn btn-primary mt-3">
                                    Apply
                                </a>

                            {% endif %}
                        </form>


                    </div>


                {% endfor %}
            {% else %}
                {% if applied_jobs %}
                    <h6 class="text-center mb-5 mt-5">You applied for all jobs none current available for the moment</h6>
                    {% else %}
                    <h6 class="text-center mb-5 mt-5">No  new jobs yet</h6>
                    {% endif %}


                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
            {% endif %}


        </div>
    </div>

    <footer class="jumbotron jumbofoot">
        <div class="container">
            <div class="row">

                <div class="col-6 col-md">
                    <h5>Menu</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/pricing">Pricing</a></li>
                        <li><a class="text-muted" href="/accounts/login/">Testing</a></li>
                        <li><a class="text-muted" href="{% url 'transactions:sourcing' %}">Sourcing</a></li>
                        <li><a class="text-muted" href="/dev">Developer</a></li>

                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Company</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/privacy">Privacy</a></li>
                        <li><a class="text-muted" href="/terms">Terms</a></li>


                    </ul>
                </div>
                <div class="col col-md">
                    <h5>Contact</h5>
                    <ul class="list-unstyled  text-small">
                        <li>
                            <a href="mailto:info@codeln.com" target="_top">
                                <i><span data-feather="mail"></span></i>
                            </a>
                        <li>
                            <a class="text-muted" href="https://www.linkedin.com/company/codeln/" target="_blank">
                                <i><span data-feather="linkedin"></span></i>
                            </a>
                        </li>
                        <li>
                            <a class="text-muted" href="https://twitter.com/Codeln_spaces" target="_blank">
                                <i><span data-feather="twitter"></span></i>
                            </a>
                        </li>
                        <li>
                            <a class="text-muted" href="https://www.facebook.com/CodelnSpaces/" target="_blank">
                                <i><span data-feather="facebook"></span></i>
                            </a>
                        </li>

                    </ul>
                </div>

            </div>
        </div>
    </footer>









{% endblock %}

frontend/templates/frontend/profile_edit_form.html
{% extends 'candidatesbase.html' %}
{% load bootstrap4 %}
{% block title %}
    developers
{% endblock %}
{%load static %}
{% block content %}
<main role="main" class="col-md-10 col-lg-10 ml-lg-auto   px-4 ">
    <div class="d-none d-lg-block">
        <nav class="navbar  navbar-light fixed-top fine border-bottom">
                    <h5 >Edit Profile</h5>
                    <ul class="nav ml-auto">



            {% if request.user.is_authenticated %}

            <li class="nav-item">
                <a  href="{% url 'account_logout' %}" style="color: black" class="nav-link" >Logout</a>
            </li>

            {% else %}

            <li class="nav-item">
                <a  href="{% url 'account_login' %}" style="color: black" class="nav-link" >Login</a>
            </li>
            <li class="nav-item">
                <a  href="{% url 'account_signup' %}" style="color: black" class="nav-link" >Register</a>
            </li>
            {% endif %}


    </ul>
                </nav>
    </div>

    <!-----md devices adaptation------>
    <div class="container d-lg-none">
        <nav class=" navbar loginbar navbar-expand-md navbar-light fixed-top ">
            <a class="logoadapt h5" style="text-decoration: none" href="">Edit Profile</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span  class="navbar-toggler-icon">
                    <span style="color: white" data-feather="menu"></span>
                </span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" style="color: white"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sidebar menu options
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/">Dashboard</a>
                            <a class="dropdown-item" href="{% url 'frontend:buildproject' %}">Build a Project</a>
                            <a class="dropdown-item" href="{% url 'students:tests' %}">Skill assessment</a>
                            <a class="dropdown-item" href="{% url 'frontend:calltoapply' %}">Companies recruiting</a>
                            <a class="dropdown-item" href="/update_profile/">My profile</a>
                        </div>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a  href="/home" style="color: white" class="nav-link" >Home</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'account_logout' %}" style="color: white" class="nav-link" >Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a  href="{% url 'account_login' %}" style="color: white" class="nav-link" >Login</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'account_signup' %}" style="color: white" class="nav-link" >Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

<div class="d-none d-lg-block" style="margin-top: 8%">

</div >

<div class="d-lg-none"  style="margin-top: 7em">

</div>
<div class="shadow-lg p-3 mt-3">
    <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-4">
                        {% bootstrap_field profile_form.github_repo %}

                    </div>
                    <div class="col-lg-4">
                        {% bootstrap_field profile_form.linkedin_url %}

                    </div>
                    <div class="col-lg-4">
                        {% bootstrap_field profile_form.portfolio %}

                    </div>

                    <div class="col-lg-4">
                        {% bootstrap_field profile_form.phone_number %}

                    </div>

                    <div class="col-lg-4">
                        {% bootstrap_field profile_form.language %}

                    </div>
                    <div class="col-lg-4">
                        {% bootstrap_field profile_form.framework %}

                    </div>
                    <div class="col-lg-4">
                        {% bootstrap_field profile_form.availabilty %}

                    </div>
                    <div class="col-lg-4">
                        <label>Are you part of the CodeLn Student Ambassador Program?</label>
                        {% bootstrap_field profile_form.csa show_label=False %}

                    </div>


                </div>
        <div class="row">
            <div class="col-lg-6">
                        {% bootstrap_field profile_form.about %}

                    </div>

        </div>



         <div class="d-flex justify-content-lg-start">
        <button class="btn primary1  col-3" style="color: white"  type="submit">Submit</button>
    </div>

            </form>

</div>















{% endblock %}