blog/urls.py
from django.urls import path

from blog.views import create_or_edit_post,post_detail,post_list

app_name = 'blog'

urlpatterns = [
    path('create_post/',create_or_edit_post,  name='create_post'),
    path('edit_post/<int:_id>/',create_or_edit_post,  name='edit_post'),
    path('', post_list, name='post_list'),
    path('post_detail/<int:post_id>', post_detail, name='post_detail'),

]

codelnmain/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from accounts.views import profile

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/<int:pk>', profile, name='view_profile'),
    path('projects/', include('projects.urls', namespace='projects')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('', include('frontend.urls', namespace='frontend')),
    path('', include('classroom.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('martor/', include('martor.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token',obtain_jwt_token),
    path('api-token-refress',refresh_jwt_token),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.page_404'
handler500 = 'frontend.views.page_500'

frontend/urls.py
from django.urls import path

from frontend.views import index, UserList
from frontend.views import home,activity,tracker,update_candidateprojects,\
    sample,inprogress,projectinvites,update_finished,invites,\
    projectdetails,pendingproject,terms,dev,pricing,howitworks,privacy,\
    report,credits,onboarddevs,onboardrecruiters,seedevs,seerecruiters,manageprojects,managetransactions,\
    editproject,deleteproject,addproject,edittransactions\
    ,deletetransaction,buildproject,calltoapply,apply,opencalltracker,competitions,newproject,\
    passedquizzes,failedquizzes,pickcandidates,update_finishedopencall,portfolio,experience,closetransaction,\
    editportfolioproject,about,management,grading,storegrades,analytics,ProfileUpdate,Profileget,Talentget,Experienceget,\
    Portfolioget,AllUsers,Userget,AllExperienceget,AllPortfolioget,ProjectAssignment
from frontend.tasks import reminderforprofiledevs,applyreminder,massmail,submission
from accounts.views import update_profile

app_name = 'frontend'
urlpatterns = [
    path('', index, name='index'),
    path('home/', home, name='home'),
    path('tracker/<int:id>', tracker, name='tracker'),
    path('dev', dev, name='dev'),
    path('howitworks', howitworks, name='howitworks'),
    path('pricing', pricing, name='pricing'),
    path('report/<int:candidate_id>/<int:transaction_id>', report, name='report'),
    path('privacy', privacy, name='privacy'),
    path('terms', terms, name='terms'),
    path('sample', sample, name='sample'),
    path('credits', credits, name='credits'),
    path('inprogress/', inprogress, name='inprogress'),
    path('invites/', invites, name='invites'),
    path('pendingproject/<int:transaction_id>', pendingproject, name='pendingproject'),
    path('projectdetails/<int:id>', projectdetails, name='projectdetails'),
    path('activity/', activity, name='my-activity'),
    path('update_profile/', update_profile, name='update-profile'),
    path('projectinvites/<int:transaction_id>/', projectinvites, name='update-profile'),
    path('update_finished/<int:candidateproject_id>/<int:transaction_id>', update_finished,
         name='update_finished'),
    path('update_finishedopencall/<int:project_id>/<int:transaction_id>', update_finishedopencall,
         name='update_finishedopencall'),
    path('update_candidateprojects/<int:candidateproject_id>/<int:transaction_id>', update_candidateprojects,
         name='update_candidateprojects'),
    path('onboarddevs',onboarddevs,name='onboarddevs'),
    path('onboardrecruiters',onboardrecruiters,name='onboardrecruiters'),
    path('seedevs',seedevs,name='seedevs'),
    path('seerecruiters',seerecruiters,name='seerecruiters'),
    path('manageprojects',manageprojects,name='manageprojects'),
    path('managetransactions',managetransactions,name='managetransactions'),
    path('editproject/<int:project_id>',editproject,name='editproject'),
    path('deleteproject/<int:project_id>',deleteproject,name='deleteproject'),
    path('edittransactions/<int:transaction_id>',edittransactions,name='edittransactions'),
    path('deletetransaction/<int:transaction_id>',deletetransaction,name='deletetransaction'),
    path('closetransaction/<int:transaction_id>',closetransaction,name='closetransaction'),
    path('addproject',addproject,name='addproject'),
    path('calltoapply',calltoapply,name='calltoapply'),
    path('buildproject',buildproject,name='buildproject'),
    path('passedquizzes',passedquizzes,name='passedquizzes'),
    path('failedquizzes',failedquizzes,name='failedquizzes'),
    path('competitions',competitions,name='competitions'),
    path('apply/<int:opportunity_id>',apply,name='apply'),
    path('opencalltracker/<int:trans_id>',opencalltracker,name='opencalltracker'),
    path('pickcandidates/<int:trans_id>/<int:candidate_id>',pickcandidates,name='pickcandidates'),
    path('reminderforprofiledevs',reminderforprofiledevs,name='reminderforprofiledevs'),
    path('applyreminder', applyreminder, name='applyreminder'),
    path('massmail', massmail, name='massmail'),
    path('submission', submission, name='submission'),
    path('portfolio',portfolio,name='portfolio'),
    path('analytics',analytics,name='analytics'),

    path('newproject',newproject,name='newproject'),
    path('experience',experience,name='experience'),
    path('editportfolioproject/<int:project_id>',editportfolioproject,name='editportfolioproject'),
    path('about',about,name='about'),
    path('management',management,name='management'),
    path('grading/<int:candidate_id>/<int:transaction_id>',grading,name='grading'),
    path('storegrades/<int:candidate_id>/<int:transaction_id>',storegrades,name='storegrades'),
    path('users/', UserList.as_view()),
    path('allusers/', AllUsers.as_view()),
    path('updater/<int:pk>', ProfileUpdate.as_view()),
    path('getuser/<int:pk>', Userget.as_view()),
    path('getprofile/<int:pk>', Profileget.as_view()),
    path('gettalent/<int:pk>', Talentget.as_view()),
    path('getexperience/<int:candidate_id>', Experienceget.as_view()),
    path('getportofolio/<int:candidate_id>', Portfolioget.as_view()),
    path('getallexperience', AllExperienceget.as_view()),
    path('getallportofolio', AllPortfolioget.as_view()),
    path('asignproject', ProjectAssignment.as_view()),




]

projects/urls.py
from django.urls import path
from projects.views import project_list, project,categories,devtypes,Projects,ProjectDetails,Allprojects,RecentProjects,MyRecentProjects,RecommendedProjects

app_name = 'projects'
urlpatterns = [
    #path('', project_categories, name='categories'y),
    path('all-projects/<int:type_id>/', project_list, name='all-projects'),
    path('devtypes/<int:dev_id>/', devtypes, name='devtypes'),
    path('categories/', categories, name='categories'),
    path('project/<int:id>/', project, name='project'),
    path('projects/<int:id>', Projects.as_view()),
    path('recommendedprojects/<int:id>', RecommendedProjects.as_view()),
    path('allprojects', Allprojects.as_view()),
    path('projectdetails/<int:pk>', ProjectDetails.as_view()),
    path('recentprojects/<int:id>', RecentProjects.as_view()),
    path('myrecentprojects/<int:id>', MyRecentProjects.as_view()),

]

transactions/urls.py
from django.urls import path

from transactions.views import process_transaction, my_invites, \
    sourcing, transaction_view,success,opencall

app_name = 'transactions'

urlpatterns = [
    # path('', project_categories, name='categories'),
    path('transaction/<int:id>/', transaction_view, name='transaction'),
    path('process_transaction/<int:id>/', process_transaction, name='process_transaction'),
    path('my-invites/', my_invites, name='my-invites'),
    path('sourcing/', sourcing, name='sourcing'),
    path('success/', success, name='success'),
    path('opencall/<int:id>/', opencall, name='opencall'),

]

frontend/models.py
from django.contrib.auth.models import User
from django.db import models

from marketplace.models import Job
from django_countries.fields import CountryField
from projects.models import Language, Framework ,Project
from transactions.models import Transaction
from separatedvaluesfield.models import SeparatedValuesField

# Create your models here.
class candidatesprojects(models.Model):
    stage = models.CharField(default='awaiting candidate', max_length=100)
    candidate = models.ForeignKey(User, on_delete=models.CASCADE,null=True,)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE,null=True,)




class submissions(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    demo = models.CharField(null=True, max_length=400)
    repo = models.CharField(null=True, max_length=400)

class Portfolio(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(null=True, max_length=200)
    description = models.CharField(null=True, max_length=400)
    repository_link = models.CharField(null=True, max_length=400)
    demo_link = models.CharField(null=True, max_length=400)
    verified = models.BooleanField(default=False)
    tech_tags = models.CharField(max_length=500, blank=True, null=True, )


class Experience(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(null=True, max_length=100)
    company = models.CharField(null=True, max_length=100)
    description = models.CharField(null=True, max_length=100)
    location = CountryField(null=True, max_length=30)
    duration = models.IntegerField(null=True)
    tech_tags = models.CharField(max_length=500, blank=True, null=True, )

class Report(models.Model):
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    requirements= SeparatedValuesField(null=True,max_length=150,token=',')
    keycompitency = SeparatedValuesField(null=True,max_length=150,token=',')
    grading = SeparatedValuesField(null=True,max_length=150,token=',')
    score = models.IntegerField(null=True)
    github = models.CharField(null=True, max_length=300)

projects/forms.py
from django import forms

from projects.models import Framework
def framework_choices():
    return tuple([(str(framework.name), framework.name) for framework in Framework.objects.all()])

class FrameworkForm(forms.Form):
    name = forms.ChoiceField(choices=framework_choices)

projects/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from marketplace.models import Job
from projects.forms import FrameworkForm
from projects.models import Project,Projecttype,Devtype,Framework
from rest_framework.permissions import IsAuthenticated
from .serializers import Projectserializer
from rest_framework import generics
import random
from django.contrib.auth.models import User
from marketplace.models import JobApplication,DevRequest
from accounts.models import Profile
class Projects(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = Projectserializer
    def get_queryset(self):
        job_id = self.kwargs['id']
        job = Job.objects.get(id=job_id)
        projects = Project.objects.all()
        tags = job.tech_stack.split(",")
        randomlist =[]
        for oneproject  in projects :
            for onetag in tags:
                if oneproject.tags.find(onetag.lower()):
                    randomlist.append(oneproject.id)
        print(randomlist)
        if len(randomlist) > 0:
            projectid = random.choice(randomlist)
        else:
            projectid = randomlist[0]


        return Project.objects.filter(pk=projectid)

class RecommendedProjects(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = Projectserializer
    def get_queryset(self):
        user_id = self.kwargs['id']
        user = User.objects.get(pk=user_id)
        userprofile = Profile.objects.get(user=user)
        projects = Project.objects.all()
        tags = userprofile.skills.split(",")
        randomlist =[]
        for oneproject  in projects :
            for onetag in tags:
                if oneproject.tags.find(onetag.lower()):
                    randomlist.append(oneproject.id)
        if len(randomlist) > 0:
            projectid = random.choice(randomlist)
        else:
            projectid = randomlist[0]

        return Project.objects.filter(pk=projectid)

class Allprojects(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = Project.objects.all()
    serializer_class = Projectserializer

class ProjectDetails(generics.RetrieveAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = Project.objects.all()
    serializer_class = Projectserializer

class RecentProjects(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = Projectserializer
    def get_queryset(self):
        user_id = self.kwargs['id']
        user = User.objects.get(pk=user_id)
        recentprojects = JobApplication.objects.filter(recruiter=user)
        project_ids = []
        for oneproject in recentprojects:
            project_ids.append(oneproject.project.id)
        return Project.objects.filter(pk__in=project_ids)
class MyRecentProjects(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = Projectserializer
    def get_queryset(self):
        user_id = self.kwargs['id']
        user = User.objects.get(pk=user_id)
        recentprojects = DevRequest.objects.filter(owner=user)[:2]
        project_ids = []
        for oneproject in recentprojects:
            project_ids.append(oneproject.project)
        return project_ids







# Create your views here.
# def project_categories(request):
#     # list all project categories
#     if request.method == 'GET':
#         return render(request, 'projects/categories.html', {})
#     elif request.method == 'POST':
#         return HttpResponse('<h2> Done </h2>')


# def project_category_list(request):
#     # list all project from above category
#     # filter projects by framework, language
#     pass

@login_required
def project_list(request,type_id):
    # TODO: filter projects by framework, language and category using django filter
    categoryname=Projecttype.objects.get(id=type_id)

    projecttypes = Project.objects.filter(projecttype_id=type_id)
    return render(request, 'projects/all_projects.html', {'projecttypes': projecttypes,'categoryname':categoryname})
@login_required
def devtypes(request,dev_id):
    # TODO: filter projects by framework, language and category using django filter

    categoryname=Devtype.objects.get(id=dev_id)
    devtypes = Project.objects.filter(devtype_id=dev_id)
    return render(request, 'projects/devtypes.html', {'devtypes':devtypes,'categoryname':categoryname})
@login_required
def categories(request):
    projecttypes = Projecttype.objects.all()
    devtypes = Devtype.objects.all()

    return render(request, 'projects/categories.html',{'projecttypes':projecttypes, 'devtypes': devtypes})

@login_required
def project(request, id):

    frameworks =Framework.objects.all()
    project = Project.objects.get(id=id)
    framework_form = FrameworkForm()
    return render(request, 'projects/project.html', {'project': project,'frameworks':frameworks,'framework_form':framework_form,})

frontend/templates/frontend/recruiter/competitions.html
{% extends 'base3.html' %}
{% block title %}
    Competitions
{% endblock %}
{% load static %}
{% block content %}

    <!---- Hero image intro----->
    <div class="jumbotron jumbotroncompetions  ">
        <div class="container  " style="height: 40vm">
            <h4 class="mt-5 col-12 col-lg-6 col-xl-6 col-sm-12 col-md-6 d-none d-lg-block"
                style="font-weight: 700;font-size: 3.0rem;">NATTERBASE  CHALLENGE</h4>
            <h4 class=" col-12 col-lg-6 col-xl-6 col-sm-12 col-md-6 d-lg-none"
                style="font-weight: 700;margin-top: 5rem">NATTERBASE  CHALLENGE</h4>


        </div>


    </div>




    <!-----how to apply------->
    <div class="position-relative overflow-hidden ">
        <section>
            <div class="row" style="margin-left: 0;margin-right: 0">
                <div class="col-12 col-lg-6 col-md-12 col-sm-12 ml-auto mr-auto text-center">
                    <h2 class="d-none d-lg-block" style="margin: 50px auto 40px auto;">Here’s What you have to do</h2>
                    <h5 class="d-lg-none" style="margin: 50px auto 40px auto;">Here’s What you have to do</h5>
                </div>

            </div>
            <div class="col-12 col-lg-6 col-md-12 col-sm-12 ml-auto mr-auto">

                <ol class="ml-lg-5 d-none d-lg-block">
                    <li style="font-size: 20px;color: #4c4d4f;"><a href="{% url 'account_signup' %}">Register or
                        login</a> as a Developer
                    </li>
                    <li style="font-size: 20px;color: #4c4d4f;">Fill out your profile</li>
                    <li style="font-size: 20px;color: #4c4d4f;">Complete the Nodejs Natterbase Challenge quiz from the
                        <a href="{% url 'frontend:calltoapply' %}"> ‘Companies recruiting’</a> section
                    </li>
                    <li style="font-size: 20px;color: #4c4d4f;">The apply button will become active(blue) submit your
                        application and a Codeln
                        representative will contact you shortly
                    </li>

                </ol>
                <ol class="d-lg-none ml-md-5 ">
                    <li style="font-size: 16px;color: #4c4d4f;"><a href="{% url 'account_signup' %}">Register or
                        login</a> as a Developer</li>
                    <li style="font-size: 16px;color: #4c4d4f;">Fill out your profile</li>
                    <li style="font-size: 16px;color: #4c4d4f;">Complete the Nodejs Natterbase Challenge quiz from the
                        <a href="{% url 'frontend:calltoapply' %}"> ‘Companies recruiting’</a> section
                    </li>
                    <li style="font-size: 16px;color: #4c4d4f;">The apply button will become active(blue) submit your
                        application and a Codeln
                        representative will contact you shortly
                    </li>


                </ol>


            </div>
        </section>
    </div>





{% endblock %}

frontend/templates/frontend/recruiter/edittransaction.html
{% extends 'recruiterbase.html' %}
{% block title %}
recruiter dashboard
{% endblock %}
{% load static %}
{% block content %}
<main role="main" class="col-md-12 ml-lg-auto  col-lg-10 px-4 ">
    <div class="d-none d-lg-block">
        <nav class="navbar  navbar-light fixed-top fine border-bottom">
                    <h5 >Edit transaction</h5>
                    <ul class="nav ml-auto">



            {% if request.user.is_authenticated %}



            <li class="nav-item">
                <a  href="{% url 'account_logout' %}" style="color: black" class="nav-link" >Logout</a>
            </li>

            {% else %}

            <li class="nav-item">
                <a  href="{% url 'account_login' %}" style="color: black" class="nav-link" >Login</a>
            </li>
            <li class="nav-item">
                <a  href="{% url 'account_signup' %}" style="color: black" class="nav-link" >Register</a>
            </li>
            {% endif %}


    </ul>
                </nav>
    </div>

    <!-----md devices adaptation------>
    <div class="container d-lg-none">
        <nav class=" navbar loginbar navbar-expand-md navbar-light fixed-top ">
            <a class="logoadapt h5" style="text-decoration: none" href="/home">Edit transaction</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span  class="navbar-toggler-icon">
                    <span style="color: white" data-feather="menu"></span>
                </span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" style="color: white"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menu
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'frontend:my-activity' %}" >Ongoing tests</a>
                            <a class="dropdown-item" href="{% url 'projects:categories' %}">Create a test</a>
                            <a class="dropdown-item" href="{% url 'transactions:sourcing' %}">Source candidates</a>
                            {% if request.user.is_staff %}
                                <a class="dropdown-item" href="{% url 'frontend:onboarddevs' %}">devs</a>
                                <a class="dropdown-item" href="{% url 'frontend:onboardrecruiters' %}">recruiters</a>
                            {% endif %}
                        </div>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a  href="/home" style="color: white" class="nav-link" >Home</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'account_logout' %}" style="color: white" class="nav-link" >Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a  href="{% url 'account_login' %}" style="color: white" class="nav-link" >Login</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'account_signup' %}" style="color: white" class="nav-link" >Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

<div class="d-none d-lg-block" style="margin-top: 6%">

</div >

<div class="d-lg-none"  style="margin-top: 7em">

</div>
<div class="row">
    <div class="col-6">


            <img style="width: 50%" src="{{ transaction.project.projectimage1 }}" alt="Card image cap">

    </div>
            <div class="col-6">


    <h6 class="card-title">{{ transaction.project }}</h6>
      <p class="card-text"><strong>Recruiter name: </strong>{{ transaction.user.first_name }}  {{ transaction.user.last_name }}</p>
      <p class="card-text"><strong>Recruiter email:</strong> {{ transaction.user.email }}</p>
      <p class="card-text"><strong>Recruiter company:</strong> {{ transaction.user.profile.company }}</p>
    <a href="{% url 'frontend:deletetransaction' transaction.id %}" class="btn btn-warning">Delete Project</a>
      <a href="{% url 'frontend:closetransaction' transaction.id %}" class="btn btn-primary">Close Project</a>

</div>
    </div>
    <div class="col-12">
        <h6>Candidates list</h6>
    <div class="card">
        <table class="table">
  <thead class="thead-light">
    <tr>
        <th scope="col">id</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
        <th scope="col">Stage</th>
        <th scope="col">grade</th>


    </tr>
  </thead>
  <tbody>
  {% for candidate in candidates %}
    <tr>
        <td>{{ candidate.candidate.id }}</td>
      <td>{{ candidate.candidate.first_name }}  {{ candidate.candidate.last_name }}</td>
      <td>{{ candidate.candidate.email }}</td>
      <td>graded</td>

        <td><span class="badge badge-primary">graded</span> </td>



    </tr>
  {% endfor %}
  {% for candidate in withoutreport %}
    <tr>
        <td>{{ candidate.candidate.id }}</td>
      <td>{{ candidate.candidate.first_name }}  {{ candidate.candidate.last_name }}</td>
      <td>{{ candidate.candidate.email }}</td>
      <td>{{ candidate.stage }}</td>
    {% if candidate.stage == 'project-completed' %}
        <td><a href="{% url 'frontend:grading' candidate.candidate_id candidate.transaction_id %}" class="btn-sm btn-success">grade</a> </td>
        {% else %}
        <td>Not yet </td>
    {% endif %}

    </tr>
  {% endfor %}

  </tbody>
</table>

    </div>

    </div>
</div>








</main>



{% endblock %}

frontend/templates/frontend/recruiter/projects.html
{% extends 'recruiterbase.html' %}
{% block title %}
recruiter dashboard
{% endblock %}
{% load static %}
{% block content %}
<main role="main" class="col-md-12 ml-lg-auto  col-lg-10 px-4 ">
    <div class="d-none d-lg-block">
        <nav class="navbar  navbar-light fixed-top fine border-bottom">
                    <h5 >Manage projects</h5>
                    <ul class="nav ml-auto">



            {% if request.user.is_authenticated %}



            <li class="nav-item">
                <a  href="{% url 'account_logout' %}" style="color: black" class="nav-link" >Logout</a>
            </li>

            {% else %}

            <li class="nav-item">
                <a  href="{% url 'account_login' %}" style="color: black" class="nav-link" >Login</a>
            </li>
            <li class="nav-item">
                <a  href="{% url 'account_signup' %}" style="color: black" class="nav-link" >Register</a>
            </li>
            {% endif %}


    </ul>
                </nav>
    </div>

    <!-----md devices adaptation------>
    <div class="container d-lg-none">
        <nav class=" navbar loginbar navbar-expand-md navbar-light fixed-top ">
            <a class="logoadapt h5" style="text-decoration: none" href="/home">Manage projects</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span  class="navbar-toggler-icon">
                    <span style="color: white" data-feather="menu"></span>
                </span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" style="color: white"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menu
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'frontend:my-activity' %}" >Ongoing tests</a>
                            <a class="dropdown-item" href="{% url 'projects:categories' %}">Create a test</a>
                            <a class="dropdown-item" href="{% url 'transactions:sourcing' %}">Source candidates</a>
                            {% if request.user.is_staff %}
                                <a class="dropdown-item" href="{% url 'frontend:onboarddevs' %}">devs</a>
                                <a class="dropdown-item" href="{% url 'frontend:onboardrecruiters' %}">recruiters</a>
                            {% endif %}
                        </div>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a  href="/home" style="color: white" class="nav-link" >Home</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'account_logout' %}" style="color: white" class="nav-link" >Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a  href="{% url 'account_login' %}" style="color: white" class="nav-link" >Login</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'account_signup' %}" style="color: white" class="nav-link" >Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

<div class="d-none d-lg-block" style="margin-top: 8%">
    <div class="row">
        <div class="col-lg-10 col-sm-6 col-md-8 col-8">
            <div class="alert alert-primary "  role="alert">
        Manage the various projects here

    </div>

        </div>
        <div class="col-lg-2 col-sm-6 col-md-4 col-4">
            <a href="{% url 'frontend:addproject' %}"><button class="btn btn-warning">Add Project</button></a>

        </div>
    </div>



</div >

<div class="d-lg-none"  style="margin-top: 7em">
    <div class="row">
        <div class="col-lg-10 col-sm-8 col-md-8 col-8">
            <div class="alert alert-primary "  role="alert">
        Manage the various projects here

    </div>

        </div>
        <div class="col col-sm-4 col-md-4 col-4">
            <a href="{% url 'frontend:addproject' %}"><button class="btn btn-warning">Add Project</button></a>

        </div>
    </div>

</div>



<div class="row" style="margin-left: 0;margin-right: 0" >



        {% for foo in projects %}

        <div class="col-lg-4 col-sm-6 mb-3 col-md-4" >
            <a href="{% url 'frontend:editproject' foo.id %}" style="text-decoration: none;">
            <div class="card" style="width:100%;height: 100%">
                <img class="img-fluid" src="{{foo.projectimage1}}" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">Project name: {{ foo.name }}
                    </p>
                    <p><span class="badge badge-primary">Level : {{ foo.level }} </span></p>

                </div>


            </div>
            </a>

        </div>
        {% endfor %}
    </div>

</main>



{% endblock %}